/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuResponsivo;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 22159663
 */
public class Entrar extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public Entrar() {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        PaneEntrar = new javax.swing.JLayeredPane();
        PanCadastro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtLogin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtCEP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtSenha1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        TxtRG = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtSenha2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        TxtCPFCadastro = new javax.swing.JTextField();
        CheckSenhaCadastro = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JSpinner();
        LblSenha = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanLogin = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JPasswordField();
        CheckSenha = new javax.swing.JCheckBox();
        LblAviso = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LblCadastrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setPreferredSize(new java.awt.Dimension(670, 470));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneEntrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanCadastro.setBackground(new java.awt.Color(51, 102, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nome Completo");

        TxtLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CEP");

        TxtCEP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCEPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha");

        TxtSenha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenha1ActionPerformed(evt);
            }
        });
        TxtSenha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSenha1KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("RG");

        TxtRG.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRGActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Confirmação de senha");

        TxtSenha2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenha2ActionPerformed(evt);
            }
        });
        TxtSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSenha2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSenha2KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CPF");

        TxtCPFCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtCPFCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCPFCadastroActionPerformed(evt);
            }
        });

        CheckSenhaCadastro.setForeground(new java.awt.Color(0, 0, 0));
        CheckSenhaCadastro.setText("Mostrar senha.");
        CheckSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSenhaCadastroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("R$");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Salário");

        TxtSalario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtSalario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TxtSalario.setValue(10.00);

        LblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblSenha.setForeground(new java.awt.Color(255, 0, 51));
        LblSenha.setText("Sua confirmação de senha não corresponde com a senha inserida.");

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Pronto");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanCadastroLayout = new javax.swing.GroupLayout(PanCadastro);
        PanCadastro.setLayout(PanCadastroLayout);
        PanCadastroLayout.setHorizontalGroup(
            PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCadastroLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanCadastroLayout.createSequentialGroup()
                        .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(CheckSenhaCadastro)
                            .addComponent(TxtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(LblSenha))
                .addGap(15, 15, 15))
        );
        PanCadastroLayout.setVerticalGroup(
            PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCadastroLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckSenhaCadastro)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(LblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(92, 92, 92))
        );

        PaneEntrar.add(PanCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanLogin.setBackground(new java.awt.Color(153, 255, 153));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Login");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CPF");

        TxtCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCPFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Senha");

        TxtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenhaActionPerformed(evt);
            }
        });

        CheckSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CheckSenha.setForeground(new java.awt.Color(0, 0, 0));
        CheckSenha.setText("Mostrar senha.");
        CheckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSenhaActionPerformed(evt);
            }
        });

        LblAviso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblAviso.setForeground(new java.awt.Color(255, 0, 51));
        LblAviso.setText("Dados cadastrais incorretos ou não registrados.");

        BtnEntrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnEntrar.setText("Entrar");
        BtnEntrar.setToolTipText("");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setToolTipText("");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LblCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblCadastrar.setForeground(new java.awt.Color(0, 204, 255));
        LblCadastrar.setText("Cadastre-se.");
        LblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblCadastrarMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Não tem conta?");

        javax.swing.GroupLayout PanLoginLayout = new javax.swing.GroupLayout(PanLogin);
        PanLogin.setLayout(PanLoginLayout);
        PanLoginLayout.setHorizontalGroup(
            PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanLoginLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLoginLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLoginLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblCadastrar)
                            .addGap(103, 103, 103))
                        .addComponent(LblAviso)
                        .addGroup(PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CheckSenha)
                            .addComponent(TxtSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanLoginLayout.createSequentialGroup()
                                .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        PanLoginLayout.setVerticalGroup(
            PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckSenha)
                .addGap(7, 7, 7)
                .addComponent(LblAviso)
                .addGap(18, 18, 18)
                .addGroup(PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEntrar)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LblCadastrar))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        PaneEntrar.add(PanLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 680, 400));

        getContentPane().add(PaneEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LblAviso.setVisible(false);
        PanCadastro.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void LblCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCadastrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LblCadastrarMouseEntered

    private void LblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCadastrarMouseClicked
        // TODO add your handling code here:
        PanLogin.setVisible(false);
        PanCadastro.setVisible(true);
        LimparTudo();
    }//GEN-LAST:event_LblCadastrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        // TODO add your handling code here:
        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        long cpf = Long.parseLong(TxtCPF.getText());

        String senha2 = "";
        char[] senha = TxtSenha.getPassword();
        senha2 = new String(senha);

        boolean status_login = obj.realizarLogin(conexao, cpf, senha2);

        String nome = "";
        int nivel = 1;

        if (status_login) {

            Menu criar = new Menu();
            try {
                Statement stml = conexao.createStatement();
                ResultSet rs = stml.executeQuery("SELECT Nome_fun, Nivel from Funcionarios WHERE CPF= " + cpf + ";");

                while (rs.next()) {
                    nome = rs.getString(1);
                    nivel = rs.getInt(2);
                }

                System.out.println(nome);

            } catch (SQLException ex) {
                Logger.getLogger(Entrar.class.getName()).log(Level.SEVERE, null, ex);
            }

            dispose();

            criar.setVisible(true);
            criar.LblNome.setText(nome);
            criar.LblNivel.setText(Integer.toString(nivel));

            if (nivel < 3) {
                criar.LblDelivery.setVisible(false);
                criar.P4.setVisible(false);

                criar.LblFornecedor.setVisible(false);
                criar.P5.setVisible(false);

                criar.LblFuncionarios.setVisible(false);
                criar.P6.setVisible(false);

            }

        } else {
            LblAviso.setVisible(true);
        }
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void CheckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSenhaActionPerformed
        // TODO add your handling code here:
        if (CheckSenha.isSelected()) {
            TxtSenha.setEchoChar((char) 0);

        } else {
            TxtSenha.setEchoChar('*');

        }
    }//GEN-LAST:event_CheckSenhaActionPerformed

    private void TxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenhaActionPerformed

    private void TxtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCPFActionPerformed

    private void TxtSenha2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSenha2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenha2KeyTyped

    private void TxtSenha2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSenha2KeyReleased
        // TODO add your handling code here:
        String txt1, txt2;

        txt1 = TxtSenha1.getText();
        txt2 = TxtSenha2.getText();

        if (txt1.equals(txt2)) {
            LblSenha.setVisible(false);
        } else {
            LblSenha.setVisible(true);
        }
    }//GEN-LAST:event_TxtSenha2KeyReleased

    private void TxtSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenha2ActionPerformed

    private void TxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginActionPerformed

    private void TxtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCEPActionPerformed

    private void TxtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRGActionPerformed

    private void CheckSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSenhaCadastroActionPerformed
        // TODO add your handling code here:
        if (CheckSenhaCadastro.isSelected()) {
            TxtSenha1.setEchoChar((char) 0);
            TxtSenha2.setEchoChar((char) 0);

        } else {
            TxtSenha1.setEchoChar('*');
            TxtSenha2.setEchoChar('*');

        }
    }//GEN-LAST:event_CheckSenhaCadastroActionPerformed

    private void TxtSenha1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSenha1KeyReleased
        // TODO add your handling code here:
        String txt1, txt2;

        txt1 = TxtSenha1.getText();
        txt2 = TxtSenha2.getText();

        if (txt1.equals(txt2)) {
            LblSenha.setVisible(false);
        } else {
            LblSenha.setVisible(true);
        }
    }//GEN-LAST:event_TxtSenha1KeyReleased

    private void TxtSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenha1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Conectar obj = new Conectar();

        String senha2 = "";
        long cep = 0;

        Connection conexao = obj.connectionMySql();

        long cpf = 0;
        String nome = "";
        String rg = "";
        float salario = (int) TxtSalario.getValue();   //Por padrao, sera 10
        char[] senha = TxtSenha1.getPassword();
        senha2 = new String(senha);

        cpf = Long.parseLong(TxtCPFCadastro.getText());
        nome = TxtLogin.getText();
        rg = TxtRG.getText();

        if (!TxtCEP.getText().equals("")) {
            cep = Long.parseLong(TxtCEP.getText());
        }

        try {

            //Connection con, long CPF, String Nome, String RG, float Salario, long CEP, String Senha, int Nivel
            obj.novoFuncionario(conexao, cpf, nome, rg, salario, cep, senha2, 1);

            obj.consultaFuncionario(conexao);
            obj.closeConnectionMySql(conexao);

            JOptionPane.showMessageDialog(null, "O cadastro de " + nome + " foi efetuado.");

            Menu criar = new Menu();

            criar.LblNome.setText(nome);

            criar.LblDelivery.setVisible(false);
            criar.P4.setVisible(false);

            criar.LblFornecedor.setVisible(false);
            criar.P5.setVisible(false);

            criar.LblFuncionarios.setVisible(false);
            criar.P6.setVisible(false);

            dispose();
            criar.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro!!" + e);
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LimparTudo(){
        TxtLogin.setText("");
        TxtSenha1.setText("");
        TxtSenha2.setText("");
        TxtCEP.setText("");
        TxtRG.setText("");
        TxtCPFCadastro.setText("");
        TxtSalario.setValue(0);
        CheckSenhaCadastro.setSelected(false);
        
        TxtCPF.setText("");
        TxtSenha.setText("");
        CheckSenha.setSelected(false);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PanLogin.setVisible(true);
        PanCadastro.setVisible(false);
        LimparTudo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtCPFCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCPFCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCPFCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JCheckBox CheckSenha;
    private javax.swing.JCheckBox CheckSenhaCadastro;
    private javax.swing.JLabel LblAviso;
    private javax.swing.JLabel LblCadastrar;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JPanel PanCadastro;
    private javax.swing.JPanel PanLogin;
    private javax.swing.JLayeredPane PaneEntrar;
    private javax.swing.JTextField TxtCEP;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtCPFCadastro;
    private javax.swing.JTextField TxtLogin;
    private javax.swing.JTextField TxtRG;
    private javax.swing.JSpinner TxtSalario;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JPasswordField TxtSenha1;
    private javax.swing.JPasswordField TxtSenha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
