/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._08;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 22159663
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public MenuInicial() {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LblNovoCardapio = new javax.swing.JLabel();
        LblNovoFornecedor = new javax.swing.JLabel();
        LblNovoFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblNovoCardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/_08/pedido.png"))); // NOI18N
        LblNovoCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblNovoCardapioMouseClicked(evt);
            }
        });

        LblNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/_08/fornecedor.png"))); // NOI18N
        LblNovoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblNovoFornecedorMouseClicked(evt);
            }
        });

        LblNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/_08/funcionario.png"))); // NOI18N
        LblNovoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblNovoFuncionarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(LblNovoFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(LblNovoCardapio)
                .addGap(118, 118, 118)
                .addComponent(LblNovoFornecedor)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblNovoFornecedor)
                    .addComponent(LblNovoFuncionario)
                    .addComponent(LblNovoCardapio))
                .addContainerGap(775, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowOpened

    private void LblNovoFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblNovoFuncionarioMouseClicked
        // TODO add your handling code here:
        
        NovoFuncionario criar = new NovoFuncionario();
        
        dispose();
        
        criar.setVisible(true);
    }//GEN-LAST:event_LblNovoFuncionarioMouseClicked

    private void LblNovoFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblNovoFornecedorMouseClicked
        // TODO add your handling code here:
        NovoFornecedor criar = new NovoFornecedor();
        
        dispose();
        
        criar.setVisible(true);
    }//GEN-LAST:event_LblNovoFornecedorMouseClicked

    private void LblNovoCardapioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblNovoCardapioMouseClicked
        // TODO add your handling code here:
        NovoCardapio criar = new NovoCardapio();
        
        dispose();
        
        criar.setVisible(true);
    }//GEN-LAST:event_LblNovoCardapioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MenuInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblNovoCardapio;
    private javax.swing.JLabel LblNovoFornecedor;
    private javax.swing.JLabel LblNovoFuncionario;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
