/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._08;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 22159663
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public MenuInicial() {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblNivel = new javax.swing.JLabel();
        BtnFuncionario = new javax.swing.JButton();
        BtnCardapio = new javax.swing.JButton();
        BtnPedido = new javax.swing.JButton();
        BtnFornecedor = new javax.swing.JButton();
        BtnInsumo = new javax.swing.JButton();
        BtnDelivery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblNome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LblNome.setText("Nome");

        LblNivel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LblNivel.setText("3");

        BtnFuncionario.setText("Gerenciar Funcionários");
        BtnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFuncionarioActionPerformed(evt);
            }
        });

        BtnCardapio.setText("Novo Item Cardápio");
        BtnCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCardapioActionPerformed(evt);
            }
        });

        BtnPedido.setText("Fazer Pedido");
        BtnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPedidoActionPerformed(evt);
            }
        });

        BtnFornecedor.setText("Novo Fornecedor");
        BtnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFornecedorActionPerformed(evt);
            }
        });

        BtnInsumo.setText("Novo Insumo");
        BtnInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsumoActionPerformed(evt);
            }
        });

        BtnDelivery.setText("Novo Delivery");
        BtnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(827, 827, 827)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                    .addComponent(BtnInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(LblNome)))
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFuncionario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(LblNivel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LblNivel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LblNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDelivery)
                    .addComponent(BtnInsumo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFornecedor)
                    .addComponent(BtnPedido))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCardapio)
                    .addComponent(BtnFuncionario))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String Nivel = LblNivel.getText();
        
        if(Nivel.equals("1")){
            BtnFuncionario.setEnabled(false);
            BtnFornecedor.setEnabled(false);
            BtnDelivery.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowActivated

    private void BtnInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsumoActionPerformed
        // TODO add your handling code here
        NovoInsumo janInsumo = new NovoInsumo();

        janInsumo.setVisible(true);
        
    }//GEN-LAST:event_BtnInsumoActionPerformed

    private void BtnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPedidoActionPerformed
        // TODO add your handling code here:
        FazerPedido janPedido = new FazerPedido();

        janPedido.setVisible(true);
    }//GEN-LAST:event_BtnPedidoActionPerformed

    private void BtnCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCardapioActionPerformed
        // TODO add your handling code here:
        NovoCardapio janCardapio = new NovoCardapio();

        janCardapio.setVisible(true);
    }//GEN-LAST:event_BtnCardapioActionPerformed

    private void BtnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeliveryActionPerformed
        // TODO add your handling code here:
        NovoDelivery janDelivery = new NovoDelivery();

        janDelivery.setVisible(true);
    }//GEN-LAST:event_BtnDeliveryActionPerformed

    private void BtnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFornecedorActionPerformed
        // TODO add your handling code here:
        NovoFornecedor janFornecedor = new NovoFornecedor();

        janFornecedor.setVisible(true);
    }//GEN-LAST:event_BtnFornecedorActionPerformed

    private void BtnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFuncionarioActionPerformed
        // TODO add your handling code here:
        MenuAdm janAdm = new MenuAdm();
        
        janAdm.setVisible(true);
    }//GEN-LAST:event_BtnFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MenuInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCardapio;
    private javax.swing.JButton BtnDelivery;
    private javax.swing.JButton BtnFornecedor;
    private javax.swing.JButton BtnFuncionario;
    private javax.swing.JButton BtnInsumo;
    private javax.swing.JButton BtnPedido;
    public javax.swing.JLabel LblNivel;
    public javax.swing.JLabel LblNome;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
